# Generated by Django 5.0.6 on 2026-08-28 20:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0003_company_domain_activity_subject_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_query', models.CharField(help_text='Exactly what the visitor typed', max_length=255)),
                ('normalized_domain', models.CharField(blank=True, db_index=True, max_length=253)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('current_step', models.CharField(blank=True, choices=[('profile', 'Finding company information'), ('signals', 'Searching recent signals'), ('analysis', 'Analyzing business situation'), ('icp', 'Evaluating ICP'), ('recommend', 'Generating recommendation')], max_length=20)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True)),
                ('client_fingerprint', models.CharField(blank=True, max_length=64)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_jobs', to='leads.company')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyIntelligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icp_fit_score', models.PositiveSmallIntegerField(default=0)),
                ('icp_fit_label', models.CharField(blank=True, max_length=20)),
                ('buying_intent', models.CharField(choices=[('high', 'High'), ('warm', 'Warm'), ('medium', 'Medium'), ('low', 'Low'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('intent_delta_pct', models.SmallIntegerField(blank=True, null=True)),
                ('engagement_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('research_confidence', models.PositiveSmallIntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('current_challenge', models.TextField(blank=True)),
                ('potential_need', models.TextField(blank=True)),
                ('recommended_services', models.JSONField(blank=True, default=list)),
                ('recommended_outreach', models.TextField(blank=True)),
                ('outreach_subject', models.CharField(blank=True, max_length=255)),
                ('stage', models.CharField(default='researched', max_length=24)),
                ('last_signal_at', models.DateTimeField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence', to='leads.company')),
                ('latest_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='intelligence.researchjob')),
            ],
            options={
                'verbose_name_plural': 'company intelligence',
                'ordering': ['-icp_fit_score'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('snippet', models.TextField(blank=True)),
                ('provider', models.CharField(help_text='ollama_web_search | ddgs', max_length=40)),
                ('query', models.CharField(help_text='The search query that surfaced this', max_length=500)),
                ('rank', models.PositiveSmallIntegerField(default=0)),
                ('kind', models.CharField(choices=[('website', 'Company website'), ('news', 'News article'), ('linkedin', 'LinkedIn'), ('jobs', 'Job listing'), ('crunchbase', 'Crunchbase'), ('web', 'Web')], default='web', max_length=24)),
                ('fetched_at', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='leads.company')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='intelligence.researchjob')),
            ],
            options={
                'ordering': ['rank', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('funding', 'Funding'), ('hiring', 'Hiring'), ('news', 'News'), ('product', 'Product'), ('leadership', 'Leadership'), ('web', 'Web activity')], max_length=20)),
                ('value', models.CharField(help_text='e.g. "Series B, $22M"', max_length=255)),
                ('strength', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('detected_at', models.DateTimeField(blank=True, null=True)),
                ('observed_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='leads.company')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='intelligence.researchjob')),
                ('sources', models.ManyToManyField(blank=True, related_name='signals', to='intelligence.source')),
            ],
            options={
                'ordering': ['-detected_at', '-observed_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('profile', 'Company profile'), ('challenge', 'Current challenge'), ('need', 'Potential need'), ('intent', 'Buying intent'), ('icp', 'ICP fit'), ('risk', 'Risk')], max_length=20)),
                ('confidence', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='leads.company')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='intelligence.researchjob')),
                ('sources', models.ManyToManyField(blank=True, related_name='claims', to='intelligence.source')),
            ],
            options={
                'ordering': ['-confidence', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='researchjob',
            index=models.Index(fields=['normalized_domain', '-created_at'], name='intelligenc_normali_a27ebb_idx'),
        ),
        migrations.AddIndex(
            model_name='researchjob',
            index=models.Index(fields=['status', '-created_at'], name='intelligenc_status_277763_idx'),
        ),
        migrations.AddIndex(
            model_name='companyintelligence',
            index=models.Index(fields=['-icp_fit_score', 'buying_intent'], name='intelligenc_icp_fit_9da041_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['company', '-fetched_at'], name='intelligenc_company_f92c12_idx'),
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.UniqueConstraint(fields=('job', 'url'), name='uniq_source_per_job'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['company', 'type'], name='intelligenc_company_762f79_idx'),
        ),
        migrations.AddIndex(
            model_name='researchclaim',
            index=models.Index(fields=['company', 'category'], name='intelligenc_company_bfa95d_idx'),
        ),
    ]
