# Generated by Django 5.0.6 on 2026-09-14 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0002_companyintelligence_stage_choices'),
        ('leads', '0004_alter_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchjob',
            name='trigger_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='researchjob',
            name='trigger_type',
            field=models.CharField(choices=[('manual', 'Requested by a person'), ('scheduled', 'Started by change monitoring')], default='manual', max_length=20),
        ),
        migrations.CreateModel(
            name='CompanyWatchState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('content_snapshot', models.TextField(blank=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_changed_at', models.DateTimeField(blank=True, null=True)),
                ('last_result', models.CharField(blank=True, choices=[('unreachable', 'Could not be fetched'), ('unchanged', 'No change'), ('changed', 'Changed')], max_length=20)),
                ('last_reason', models.CharField(blank=True, max_length=200)),
                ('consecutive_unchanged', models.PositiveIntegerField(default=0)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('next_check_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watch_state', to='leads.company')),
            ],
            options={
                'ordering': ['next_check_at'],
            },
        ),
    ]
