# Generated by Django 5.0.6 on 2026-09-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0003_researchjob_trigger_reason_researchjob_trigger_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companywatchstate',
            name='last_trend_scan_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companywatchstate',
            name='next_trend_scan_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
