# Generated by Django 5.0.6 on 2026-08-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiqualification',
            name='recommended_action',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aiqualification',
            name='recommended_service',
            field=models.TextField(blank=True),
        ),
    ]
