# Generated by Django 5.0.6, then hand-extended with the domain backfill and
# duplicate-merge in `backfill_domains` below.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_domains(apps, schema_editor):
    """
    Derive Company.domain from existing websites, merging any rows that turn
    out to be the same company.

    The old code deduped with an exact, case-sensitive `get_or_create(name=...)`,
    so "Acme" / "Acme Inc." / a second submission with a trailing space are all
    separate rows today. Writing domains without merging first would violate the
    unique constraint added above, so the merge has to happen here.
    """
    from leads.companies import normalize_domain

    Company = apps.get_model("leads", "Company")
    Lead = apps.get_model("leads", "Lead")

    winners: dict[str, int] = {}

    for company in Company.objects.order_by("id").iterator():
        domain = normalize_domain(company.website) or normalize_domain(company.name)
        if not domain:
            continue

        incumbent_id = winners.get(domain)
        if incumbent_id is None:
            company.domain = domain
            company.save(update_fields=["domain"])
            winners[domain] = company.id
            continue

        # Same company under a second name: repoint its leads at the row that
        # claimed the domain first, then drop the duplicate.
        Lead.objects.filter(company_id=company.id).update(company_id=incumbent_id)
        company.delete()


def unbackfill_domains(apps, schema_editor):
    """Reverse: clear domains. Merged rows are not resurrected — that's lossy
    by nature, but the column is additive so nothing downstream breaks."""
    Company = apps.get_model("leads", "Company")
    Company.objects.update(domain=None)


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_aiqualification_recommended_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name_plural': 'companies'},
        ),
        migrations.AddField(
            model_name='activity',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='leads.company'),
        ),
        migrations.AddField(
            model_name='activity',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='domain',
            field=models.CharField(blank=True, db_index=True, max_length=253, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='company',
            name='logo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='company',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leadscore',
            name='intent_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leadscore',
            name='urgency_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='leads.lead'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('created', 'Lead created'), ('duplicate_submission', 'Duplicate submission'), ('requalify_requested', 'Re-qualification requested'), ('qualification_failed', 'Qualification failed'), ('high_intent', 'Routed to sales'), ('nurture', 'Routed to nurture'), ('assigned', 'Assigned'), ('research_started', 'Research started'), ('research_completed', 'Research completed'), ('research_failed', 'Research failed'), ('signal_detected', 'Signal detected')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['company', '-created_at'], name='leads_activ_company_85651c_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['lead', '-created_at'], name='leads_activ_lead_id_b402c8_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['industry'], name='leads_compa_industr_d9f161_idx'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(check=models.Q(('lead__isnull', False), ('company__isnull', False), _connector='OR'), name='activity_has_subject'),
        ),
        migrations.RunPython(backfill_domains, unbackfill_domains),
    ]
