# Generated by Django 5.0.6 on 2026-09-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_company_domain_activity_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('created', 'Lead created'), ('duplicate_submission', 'Duplicate submission'), ('requalify_requested', 'Re-qualification requested'), ('qualification_failed', 'Qualification failed'), ('high_intent', 'Routed to sales'), ('nurture', 'Routed to nurture'), ('assigned', 'Assigned'), ('research_started', 'Research started'), ('research_completed', 'Research completed'), ('research_failed', 'Research failed'), ('signal_detected', 'Signal detected'), ('change_detected', 'Change detected by monitoring')], max_length=50),
        ),
    ]
